### ISSUE TITLE
Swagger.io subproject is not compiling because of libraries infix

### ISSUE THREAD

**Issue by thenanox** [OnPositive/aml#21]
Hello,

I just saw this repo and im really interested in the ecosystem around Raml 1.0. I've been helping on raml-js-parser and actively using it. Right now im working with Java in mind. This repo has cool tools :). I got here from jax-rs-to-raml repo, and raml 1.0 support branch.

I checked that build is not working because the subproject swagger.io is not compiling. Test number 3 is failing. This is due to libraries been transformed into swagger with yaml are not infixed with "." in paths in declarations.

I made a PR #20. I hope it helps

**Comment by thenanox** [comment]
PS: PR #20 is not working because registry subproject is not correctly versiones and reactor maven build its after swagger.io when its needed before. Change in modules section in parent pom, reordering the build and versioning in registry subproject should make it work properly

**Comment by thenanox** [comment]
PS2: Also javacodegen subproject is not working because basicgenerator has wrong javadoc :)

Ive refactored everything and PR #20 should work now

**Comment by petrochenko-pavel-a** [comment]
Hi @thenanox  thanks a lot for your contribution, right now there is a bit of mess in the project organization, (I have introduced registry and started to work on the server for it but was distracted to another project). 

Hopefully I am finalizing last bits on the hot stage of it and then will be back to `aml`.

B.T.W how are you using RAML?

P.S. Build still does not passes for me - will look later today.

Regards,
Pavel

**Comment by thenanox** [comment]
Hi @petrochenko-pavel-a,

I think build didn't complete on PR because it consumed too much memory in travis build...it was an unexpected error.

We are using RAML as the interface main language for different clients in our company, we help in API-first designs for them.

I'm interested in all the tools around RAML.Its the only thing i think it needs to compete with swagger right now :)

Fernando
